security:
  oauth2:
    client:
      client-id: first-client
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      scope: read
      client-authentication-scheme: header
      grant-type: password
      resource-ids:
        - serviceA
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key

server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true


logging:
  level:
    org.springframework.security: debug